career-stats-settings:
    data:
        initialVisited: true
        welcomedSeason: 10
    schemaVersion: 1
champ-grid-settings:
    data:
        sortOrder: "byMastery"
    schemaVersion: 1
champ-select:
    data:
        skins:
            1: 1000
            10: 10007
            101: 101000
            102: 102000
            103: 103007
            104: 104018
            105: 105000
            106: 106000
            107: 107000
            11: 11002
            110: 110000
            111: 111004
            112: 112000
            113: 113000
            114: 114000
            115: 115000
            117: 117004
            119: 119000
            12: 12000
            120: 120000
            121: 121000
            122: 122000
            126: 126000
            13: 13000
            131: 131000
            133: 133000
            14: 14000
            142: 142000
            143: 143000
            15: 15000
            150: 150000
            154: 154000
            157: 157000
            16: 16000
            161: 161000
            163: 163000
            164: 164000
            17: 17000
            18: 18000
            2: 2000
            20: 20000
            201: 201000
            202: 202000
            203: 203000
            21: 21017
            22: 22002
            222: 222000
            23: 23002
            235: 235000
            236: 236000
            238: 238000
            24: 24001
            245: 245000
            25: 25004
            254: 254000
            26: 26000
            266: 266000
            267: 267000
            268: 268000
            27: 27000
            28: 28000
            29: 29000
            3: 3000
            30: 30000
            31: 31003
            32: 32000
            33: 33000
            34: 34000
            35: 35004
            350: 350000
            36: 36000
            39: 39000
            4: 4000
            41: 41000
            412: 412000
            42: 42000
            420: 420000
            421: 421000
            427: 427000
            429: 429000
            43: 43000
            432: 432000
            44: 44000
            45: 45002
            497: 497000
            5: 5000
            50: 50000
            51: 51019
            516: 516000
            517: 517001
            518: 518000
            523: 523000
            53: 53003
            54: 54000
            55: 55000
            555: 555000
            56: 56000
            57: 57000
            58: 58000
            59: 59000
            6: 6000
            60: 60000
            61: 61001
            62: 62000
            63: 63002
            64: 64003
            67: 67000
            68: 68000
            7: 7000
            74: 74000
            75: 75000
            77: 77000
            78: 78004
            79: 79000
            80: 80000
            81: 81000
            82: 82004
            84: 84000
            85: 85000
            86: 86000
            875: 875000
            89: 89000
            9: 9000
            90: 90000
            91: 91000
            92: 92020
            96: 96000
            98: 98000
            99: 99004
        spells:
            1020:
            - 12
            - 4
            1200:
            - 4
            - 7
            400:
            - 11
            - 4
            420:
            - 14
            - 4
            430:
            - 14
            - 4
            440:
            - 14
            - 4
            450:
            - 7
            - 4
            700:
            - 11
            - 4
            900:
            - 14
            - 4
            920:
            - 30
            - 31
    schemaVersion: 1
clash-tutorial:
    data:
        captainInviteStep: true
        captainLockinStep: true
        captainRewardStep: true
        captainRoleStep: true
        captainTicketStep: true
        initialized: true
        memberJoinTeamStep: true
        memberLockinStep: true
        memberRewardStep: true
        memberRoleStep: true
        memberTicketStep: true
        rosterDetailsModalLogoStep: true
        rosterDetailsModalNameTagStep: true
        smsButtonStep: true
        version: 3
    schemaVersion: 1
closed-conversations:
    data:
        closed-conversations: "{\r\n    \"1160327\": 1479920210314\r\n}"
        closedJson: "{\r\n    \"1160327\": 1479564001085,\r\n    \"13251306\": 1479563988471,\r\n    \"13520489\": 1479563997041,\r\n    \"3535783\": 1479563995433,\r\n    \"3932038\": 1479564003962,\r\n    \"4656718\": 1479564009411,\r\n    \"4b7d1209-fff2-4d32-b241-5c9073c58eab\": 1479564014887,\r\n    \"5026205\": 1479563990910,\r\n    \"766821\": 1479564008136,\r\n    \"8176e69a-4fde-40b6-a20a-dcb7ad6e5604\": 1479564011555,\r\n    \"9543555\": 1479563985568,\r\n    \"d9bbcc86-abcd-4f4d-aa8e-fee0fbcd0c4b\": 1479564013400\r\n}"
    schemaVersion: 0
custom-spell-selections:
    data:
        custom-spell-selections:
            spell1: 12
            spell2: 4
    schemaVersion: 0
emotes:
    data:
        newEmotes:
        - 3151
        - 1502
        - 3453
        - 3460
        - 3112
        - 3004
        - 3141
        - 3191
        - 3168
        - 3440
        - 3249
    schemaVersion: 1
eos-2019-bell-notification_SR_1:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2019-bell-notification_SR_2:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2019-bell-notification_SR_3:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2019-bell-notification_TFT_1:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2019-bell-notification_TFT_2:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2019-bell-notification_TFT_3:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2020-bell-notification_SR_2:
    data:
        notificationShown: true
    schemaVersion: 1
lol-chat:
    data:
        chatFilterDisabled: true
        linkClickWarningEnabled: false
    schemaVersion: 0
lol-clash:
    data:
        clash-login-modal-seen: true
        clash-start-modal-seen: true
    schemaVersion: 1
lol-collection-champions:
    data:
        groupingDropdownKey: "role"
        lastVisitTime: 1599152424183
        sortingDropdownKey: ""
        unownedFilter: "none"
    schemaVersion: 1
lol-collection-chromas:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1586207481346
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 2
lol-collection-summoner-icons:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1590962119120
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 2
lol-eternals:
    data:
        firstTouchModalSeen: true
    schemaVersion: 0
lol-home-hubs:
    data:
        galaxies-2020:
            watchedIntro: true
        karma-2020:
            voteCast: "pt_br_todos_pela_educacao"
    schemaVersion: 1
lol-honor:
    data:
        dayOneSeen: true
    schemaVersion: 1
lol-leagues:
    data:
        betterRewardsDayOneSeen: true
        last-end-of-split-notification: 9.200000
        last-split-end-notification: 10.300000
        last-split-start-modal: 10.300000
        season-memorial-modal: 9
        season-start-takeover:
            season: 10
    schemaVersion: 1
lol-loot:
    data:
        betterRewardsDayOneSeen: true
    schemaVersion: 1
lol-notifications:
    data:
        rgmNotificationTimestamp: 1604956834892
    schemaVersion: 1
lol-npe-tutorial-path:
    data:
        hasSeenTutorialPath: false
        hasSkippedTutorialPath: false
        shouldSeeNewPlayerExperience: false
    schemaVersion: 1
lol-parties:
    data:
        hasSeenOpenPartyFirstExperience: true
        hasSeenOpenPartyTooltip: true
    schemaVersion: 1
lol-player-behavior:
    data:
        codeOfConductAccepted: true
    schemaVersion: 0
lol-premade-voice:
    data:
        autoJoin: true
        inputMode: "voiceActivity"
        muteOnConnect: false
        pushToTalkKey: "[v]"
        showFirstExperienceInGame: false
        showFirstExperienceInLCU: false
    schemaVersion: 1
lol-profiles:
    data:
        ranked-reference-modal-login-seen-for-season: 10
    schemaVersion: 0
lol-regalia:
    data:
        regalia-login-modal-seen: true
    schemaVersion: 1
lol-revivals:
    data:
        isEligible: false
        isFirstTouch: false
    schemaVersion: 0
lol-skins-viewer:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1590698673654
        sortingDropdownKey: "acquisitionDate"
        unownedFilter: false
    schemaVersion: 2
lol-tft:
    data:
        previouslySeenSeasons: "S2_WarOfElements,S3_Galaxies-parties,S3_Galaxies-pass,S3_5_Galaxies-pass"
    schemaVersion: 1
lol-tutorial:
    data:
        Map11_URF_TutorialSeen: true
        Map21_GAMEMODEX_TutorialSeen: true
        Map22_TFT_TutorialSeen: true
        championSelectRunesTooltipSeenCount: 9
        championSelectSkinPurchaseNotificationDisplayed: true
        emotesTutotorialModalDisplayed: true
        perksCreateNewPageSeen: true
        perksPresetPagesSeen: true
        perksPrimaryPathSeen: true
        perksSecondaryPathSeen: true
        perksStatModsSeen: true
        rpChangeEatDisplayed: true
        thirdArcadeEventNotificationDisplayed: true
    schemaVersion: 1
personalized-offers:
    data:
        lastViewedTimestamp: "2020-05-22T18:48:03.067Z"
    schemaVersion: 1
runes-settings:
    data:
        tierFilters:
        -   filterOn: false
            tier: 1
        -   filterOn: false
            tier: 2
        -   filterOn: true
            tier: 3
    schemaVersion: 1
