career-stats-settings:
    data:
        initialVisited: true
        welcomedSeason: 10
    schemaVersion: 1
champ-grid-settings:
    data:
        sortOrder: "byMastery"
    schemaVersion: 1
champ-select:
    data:
        skins:
            103: 103000
            11: 11000
            110: 110009
            115: 115000
            117: 117000
            119: 119001
            126: 126000
            133: 133000
            142: 142000
            145: 145000
            15: 15000
            157: 157000
            17: 17000
            18: 18001
            19: 19000
            2: 2000
            201: 201000
            202: 202000
            21: 21000
            22: 22000
            222: 222000
            235: 235000
            236: 236004
            238: 238000
            254: 254000
            26: 26000
            266: 266010
            268: 268000
            27: 27000
            29: 29007
            30: 30000
            36: 36000
            4: 4000
            412: 412000
            42: 42000
            429: 429002
            432: 432000
            44: 44000
            45: 45000
            498: 498003
            51: 51011
            516: 516000
            518: 518000
            523: 523000
            53: 53000
            54: 54000
            55: 55000
            555: 555000
            59: 59000
            6: 6000
            61: 61008
            63: 63000
            67: 67010
            69: 69000
            74: 74000
            78: 78000
            8: 8000
            81: 81005
            82: 82000
            83: 83000
            85: 85000
            86: 86000
            9: 9000
            96: 96000
            98: 98000
            99: 99000
        spells:
            1020:
            - 12
            - 4
            1200:
            - 11
            - 4
            400:
            - 7
            - 4
            420:
            - 7
            - 4
            430:
            - 7
            - 4
            440:
            - 7
            - 4
            450:
            - 14
            - 4
            700:
            - 7
            - 4
            840:
            - 12
            - 14
            900:
            - 7
            - 4
            920:
            - 31
            - 30
    schemaVersion: 1
clash-tutorial:
    data:
        captainInviteStep: true
        captainLockinStep: true
        captainRewardStep: true
        captainRoleStep: true
        captainTicketStep: true
        initialized: true
        memberJoinTeamStep: true
        memberLockinStep: true
        memberRewardStep: true
        memberRoleStep: true
        memberTicketStep: true
        rosterDetailsModalLogoStep: true
        rosterDetailsModalNameTagStep: true
        smsButtonStep: true
        version: 2
    schemaVersion: 1
closed-conversations:
    data:
        closedJson: "{\r\n    \"13251306\": 1479325888308,\r\n    \"16341026\": 1479325897867,\r\n    \"487984\": 1479325905394\r\n}"
    schemaVersion: 0
custom-spell-selections:
    data:
        custom-spell-selections:
            spell1: 7
            spell2: 4
    schemaVersion: 0
emotes:
    data:
        newEmotes:
        - 1478
        - 3461
        - 3150
        - 3168
        - 3441
        - 997
        - 3004
        - 3409
        - 3343
        - 3003
        - 3002
    schemaVersion: 1
eos-2018-bell-notification:
    data:
        notificationShown: 3
    schemaVersion: 1
eos-2018-tooltip:
    data:
        shown: "Y"
    schemaVersion: 1
eos-2019-bell-notification_SR_1:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2019-bell-notification_SR_2:
    data:
        notificationShown: true
    schemaVersion: 1
eos-2019-bell-notification_SR_3:
    data:
        notificationShown: true
    schemaVersion: 1
lol-champ-select:
    data:
        favorites:
            bottom:
            - 42
            - 45
    schemaVersion: 0
lol-chat:
    data:
        chatFilterDisabled: true
        linkClickWarningEnabled: null
    schemaVersion: 0
lol-clash:
    data:
        clash-login-modal-seen: true
        clash-start-modal-seen: true
    schemaVersion: 1
lol-collection-champions:
    data:
        groupingDropdownKey: "ownership"
        lastVisitTime: 1591202804776
        sortingDropdownKey: "alphabetical"
        unownedFilter: "owned"
    schemaVersion: 1
lol-collection-summoner-icons:
    data:
        groupingDropdownKey: "myCollection"
        lastVisitTime: 1589380409351
        sortingDropdownKey: "acquisitionDate"
        unavailableFilter: false
        unownedFilter: false
    schemaVersion: 2
lol-eternals:
    data:
        firstTouchModalSeen: true
    schemaVersion: 0
lol-home-hubs:
    data:
        galaxies-2020:
            watchedIntro: true
        karma-2020:
            voteCast: "pt_br_todos_pela_educacao"
        pulsefire-2020:
            watchedIntro: true
    schemaVersion: 1
lol-honor:
    data:
        dayOneSeen: true
    schemaVersion: 1
lol-leagues:
    data:
        betterRewardsDayOneSeen: true
        last-split-end-notification: 10.100000
        last-split-start-modal: 10.200000
        season-memorial-modal: 9
        season-start-takeover:
            season: 10
    schemaVersion: 1
lol-loot:
    data:
        betterRewardsDayOneSeen: true
    schemaVersion: 1
lol-notifications:
    data:
        disableEsportsNotifications: false
        rgmNotificationTimestamp: 1589552397156
    schemaVersion: 1
lol-npe-tutorial-path:
    data:
        hasSeenTutorialPath: false
        hasSkippedTutorialPath: false
        shouldSeeNewPlayerExperience: false
    schemaVersion: 1
lol-parties:
    data:
        hasSeenOpenPartyFirstExperience: true
        hasSeenOpenPartyTooltip: true
    schemaVersion: 1
lol-premade-voice:
    data:
        autoJoin: true
        inputMode: "voiceActivity"
        muteOnConnect: false
        pushToTalkKey: "[v]"
        showFirstExperienceInGame: false
        showFirstExperienceInLCU: false
    schemaVersion: 1
lol-regalia:
    data:
        regalia-login-modal-seen: true
    schemaVersion: 1
lol-revivals:
    data:
        isEligible: false
        isFirstTouch: false
    schemaVersion: 0
lol-skins-viewer:
    data:
        groupingDropdownKey: "groupByTier"
        lastVisitTime: 1589380400821
        sortingDropdownKey: "groupIdDescending"
        unownedFilter: "none"
    schemaVersion: 1
lol-tft:
    data:
        previouslySeenSeasons: "S2_WarOfElements"
    schemaVersion: 1
lol-tutorial:
    data:
        Map11_URF_TutorialSeen: true
        Map20_ODYSSEY_TutorialSeen: true
        Map21_GAMEMODEX_TutorialSeen: true
        Map22_TFT_TutorialSeen: true
        championSelectRunesTooltipSeenCount: 10
        championSelectSkinPurchaseNotificationDisplayed: true
        emotesTutotorialModalDisplayed: true
        perksCreateNewPageSeen: true
        perksPresetPagesSeen: true
        perksPrimaryPathSeen: true
        perksSecondaryPathSeen: true
        perksStatModsSeen: true
        rpChangeEatDisplayed: true
        secondArcadeEventNotificationDisplayed: true
        thirdArcadeEventNotificationDisplayed: true
    schemaVersion: 1
parties-settings:
    data:
        Parties:
            defaultPartyType: "open"
    schemaVersion: 0
personalized-offers:
    data:
        lastViewedTimestamp: "2020-05-31T01:30:40.116Z"
    schemaVersion: 1
