page-settings:
    data:
        pages:
        -   autoModifiedSelections: []
            current: false
            id: 1831858514
            isActive: false
            isDeletable: true
            isEditable: true
            isValid: true
            lastModified: 0
            name: "Voli"
            order: 0
            primaryStyleId: 8400
            selectedPerkIds:
            - 8439
            - 8463
            - 8429
            - 8444
            - 8304
            - 8410
            subStyleId: 8300
        -   autoModifiedSelections: []
            current: false
            id: 1912546663
            isActive: false
            isDeletable: true
            isEditable: true
            isValid: true
            lastModified: 0
            name: "Nasus"
            order: 1
            primaryStyleId: 8100
            selectedPerkIds:
            - 8112
            - 8143
            - 8138
            - 8134
            - 8243
            - 8210
            subStyleId: 8200
        -   autoModifiedSelections: []
            current: true
            id: 606779305
            isActive: false
            isDeletable: true
            isEditable: true
            isValid: true
            lastModified: 0
            name: "teemo"
            order: 2
            primaryStyleId: 8200
            selectedPerkIds:
            - 8214
            - 8226
            - 8234
            - 8237
            - 8135
            - 8139
            subStyleId: 8100
        -   autoModifiedSelections: []
            current: false
            id: 54
            isActive: false
            isDeletable: false
            isEditable: false
            isValid: true
            lastModified: 0
            name: "Inspira\xE7\xE3o: O Atemporal"
            order: 2147483638
            primaryStyleId: 8300
            selectedPerkIds:
            - 8326
            - 8345
            - 8321
            - 8347
            - 8451
            - 8430
            subStyleId: 8400
        -   autoModifiedSelections: []
            current: false
            id: 53
            isActive: false
            isDeletable: false
            isEditable: false
            isValid: true
            lastModified: 0
            name: "Feiti\xE7aria: A Calamidade"
            order: 2147483639
            primaryStyleId: 8200
            selectedPerkIds:
            - 8229
            - 8226
            - 8210
            - 8236
            - 8138
            - 8105
            subStyleId: 8100
        -   autoModifiedSelections: []
            current: false
            id: 52
            isActive: false
            isDeletable: false
            isEditable: false
            isValid: true
            lastModified: 0
            name: "Precis\xE3o: O Perfeito"
            order: 2147483640
            primaryStyleId: 8000
            selectedPerkIds:
            - 8005
            - 9111
            - 9104
            - 8014
            - 8234
            - 8236
            subStyleId: 8200
        -   autoModifiedSelections: []
            current: false
            id: 51
            isActive: false
            isDeletable: false
            isEditable: false
            isValid: true
            lastModified: 0
            name: "Domina\xE7\xE3o: O Carrasco"
            order: 2147483641
            primaryStyleId: 8100
            selectedPerkIds:
            - 8112
            - 8126
            - 8120
            - 8135
            - 9111
            - 8014
            subStyleId: 8000
        -   autoModifiedSelections: []
            current: false
            id: 50
            isActive: false
            isDeletable: false
            isEditable: false
            isValid: true
            lastModified: 0
            name: "Determina\xE7\xE3o: O Colosso"
            order: 2147483642
            primaryStyleId: 8400
            selectedPerkIds:
            - 8437
            - 8242
            - 8430
            - 8451
            - 8224
            - 8237
            subStyleId: 8200
        perShardPerkBooks:
            br1:
                currentPageId: 53
                pages:
                -   autoModifiedSelections: []
                    current: false
                    id: 1831858514
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1599154108016
                    name: "talon"
                    order: 0
                    primaryStyleId: 8000
                    selectedPerkIds:
                    - 8010
                    - 8009
                    - 9105
                    - 8014
                    - 8143
                    - 8105
                    - 5008
                    - 5008
                    - 5003
                    subStyleId: 8100
                -   autoModifiedSelections: []
                    current: false
                    id: 606779305
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1599086431046
                    name: "ORNN"
                    order: 2
                    primaryStyleId: 8300
                    selectedPerkIds:
                    - 8351
                    - 8304
                    - 8321
                    - 8347
                    - 8139
                    - 8134
                    - 5008
                    - 5008
                    - 5003
                    subStyleId: 8100
                -   autoModifiedSelections: []
                    current: false
                    id: 644424539
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1590966924701
                    name: "Blitz"
                    order: 3
                    primaryStyleId: 8100
                    selectedPerkIds:
                    - 8112
                    - 8139
                    - 8138
                    - 8135
                    - 8275
                    - 8234
                    - 5005
                    - 5008
                    - 5002
                    subStyleId: 8200
                -   autoModifiedSelections: []
                    current: false
                    id: 1731866095
                    isActive: false
                    isDeletable: true
                    isEditable: true
                    isValid: true
                    lastModified: 1591482645436
                    name: "riven"
                    order: 3
                    primaryStyleId: 8000
                    selectedPerkIds:
                    - 8010
                    - 9111
                    - 9105
                    - 8014
                    - 8313
                    - 8347
                    - 5005
                    - 5008
                    - 5002
                    subStyleId: 8300
        settings:
            gameplayPatchVersionSeen: "9.23"
            gameplayUpdatedPerksSeen:
            - 8358
            gridModeEnabled: false
            showLongDescriptions: false
            showPresetPages: true
    schemaVersion: 5
pages:
-   current: false
    formatVersion: 4
    id: 1831858514
    isActive: false
    isDeletable: true
    isEditable: true
    isValid: true
    name: "Voli"
    order: 5
    primaryStyleId: 8400
    selectedPerkIds:
    - 8439
    - 8463
    - 8429
    - 8444
    - 8304
    - 8410
    subStyleId: 8300
-   current: false
    formatVersion: 4
    id: 1912546663
    isActive: false
    isDeletable: true
    isEditable: true
    isValid: true
    name: "Nasus"
    order: 6
    primaryStyleId: 8100
    selectedPerkIds:
    - 8112
    - 8143
    - 8138
    - 8134
    - 8243
    - 8210
    subStyleId: 8200
-   current: true
    formatVersion: 4
    id: 606779305
    isActive: false
    isDeletable: true
    isEditable: true
    isValid: true
    name: "teemo"
    order: 7
    primaryStyleId: 8200
    selectedPerkIds:
    - 8214
    - 8226
    - 8234
    - 8237
    - 8135
    - 8139
    subStyleId: 8100
-   current: false
    formatVersion: 4
    id: 54
    isActive: false
    isDeletable: false
    isEditable: false
    isValid: true
    name: "Inspira\xE7\xE3o: O Atemporal"
    order: 2147483638
    primaryStyleId: 8300
    selectedPerkIds:
    - 8326
    - 8345
    - 8321
    - 8347
    - 8451
    - 8430
    subStyleId: 8400
-   current: false
    formatVersion: 4
    id: 53
    isActive: false
    isDeletable: false
    isEditable: false
    isValid: true
    name: "Feiti\xE7aria: A Calamidade"
    order: 2147483639
    primaryStyleId: 8200
    selectedPerkIds:
    - 8229
    - 8226
    - 8210
    - 8236
    - 8138
    - 8105
    subStyleId: 8100
-   current: false
    formatVersion: 4
    id: 52
    isActive: false
    isDeletable: false
    isEditable: false
    isValid: true
    name: "Precis\xE3o: O Perfeito"
    order: 2147483640
    primaryStyleId: 8000
    selectedPerkIds:
    - 8005
    - 9111
    - 9104
    - 8014
    - 8234
    - 8236
    subStyleId: 8200
-   current: false
    formatVersion: 4
    id: 51
    isActive: false
    isDeletable: false
    isEditable: false
    isValid: true
    name: "Domina\xE7\xE3o: O Carrasco"
    order: 2147483641
    primaryStyleId: 8100
    selectedPerkIds:
    - 8112
    - 8126
    - 8120
    - 8135
    - 9111
    - 8014
    subStyleId: 8000
-   current: false
    formatVersion: 4
    id: 50
    isActive: false
    isDeletable: false
    isEditable: false
    isValid: true
    name: "Determina\xE7\xE3o: O Colosso"
    order: 2147483642
    primaryStyleId: 8400
    selectedPerkIds:
    - 8437
    - 8242
    - 8430
    - 8451
    - 8224
    - 8237
    subStyleId: 8200
settings:
    gridModeEnabled: false
    showLongDescriptions: false
    showPresetPages: true
